if not love then love = {} end
if not love.filesystem then love.filesystem = {} end
return {
	["unmount"] = { tag = "var", contents = "love.filesystem.unmount", value = love.filesystem.unmount},
	["write"] = { tag = "var", contents = "love.filesystem.write", value = love.filesystem.write},
	["set-identity"] = { tag = "var", contents = "love.filesystem.setIdentity", value = love.filesystem.setIdentity},
	["get-executable-path"] = { tag = "var", contents = "love.filesystem.getExecutablePath", value = love.filesystem.getExecutablePath},
	["init"] = { tag = "var", contents = "love.filesystem.init", value = love.filesystem.init},
	["set-symlinks-enabled"] = { tag = "var", contents = "love.filesystem.setSymlinksEnabled", value = love.filesystem.setSymlinksEnabled},
	["is-symlink"] = { tag = "var", contents = "love.filesystem.isSymlink", value = love.filesystem.isSymlink},
	["append"] = { tag = "var", contents = "love.filesystem.append", value = love.filesystem.append},
	["get-user-directory"] = { tag = "var", contents = "love.filesystem.getUserDirectory", value = love.filesystem.getUserDirectory},
	["create-directory"] = { tag = "var", contents = "love.filesystem.createDirectory", value = love.filesystem.createDirectory},
	["lines"] = { tag = "var", contents = "love.filesystem.lines", value = love.filesystem.lines},
	["exists"] = { tag = "var", contents = "love.filesystem.exists", value = love.filesystem.exists},
	["new-file"] = { tag = "var", contents = "love.filesystem.newFile", value = love.filesystem.newFile},
	["get-save-directory"] = { tag = "var", contents = "love.filesystem.getSaveDirectory", value = love.filesystem.getSaveDirectory},
	["mount"] = { tag = "var", contents = "love.filesystem.mount", value = love.filesystem.mount},
	["get-require-path"] = { tag = "var", contents = "love.filesystem.getRequirePath", value = love.filesystem.getRequirePath},
	["get-working-directory"] = { tag = "var", contents = "love.filesystem.getWorkingDirectory", value = love.filesystem.getWorkingDirectory},
	["get-size"] = { tag = "var", contents = "love.filesystem.getSize", value = love.filesystem.getSize},
	["set-fused"] = { tag = "var", contents = "love.filesystem.setFused", value = love.filesystem.setFused},
	["is-fused"] = { tag = "var", contents = "love.filesystem.isFused", value = love.filesystem.isFused},
	["get-directory-items"] = { tag = "var", contents = "love.filesystem.getDirectoryItems", value = love.filesystem.getDirectoryItems},
	["set-source"] = { tag = "var", contents = "love.filesystem.setSource", value = love.filesystem.setSource},
	["set-require-path"] = { tag = "var", contents = "love.filesystem.setRequirePath", value = love.filesystem.setRequirePath},
	["new-file-data"] = { tag = "var", contents = "love.filesystem.newFileData", value = love.filesystem.newFileData},
	["are-symlinks-enabled"] = { tag = "var", contents = "love.filesystem.areSymlinksEnabled", value = love.filesystem.areSymlinksEnabled},
	["get-identity"] = { tag = "var", contents = "love.filesystem.getIdentity", value = love.filesystem.getIdentity},
	["get-last-modified"] = { tag = "var", contents = "love.filesystem.getLastModified", value = love.filesystem.getLastModified},
	["get-appdata-directory"] = { tag = "var", contents = "love.filesystem.getAppdataDirectory", value = love.filesystem.getAppdataDirectory},
	["get-source"] = { tag = "var", contents = "love.filesystem.getSource", value = love.filesystem.getSource},
	["load"] = { tag = "var", contents = "love.filesystem.load", value = love.filesystem.load},
	["remove"] = { tag = "var", contents = "love.filesystem.remove", value = love.filesystem.remove},
	["get-real-directory"] = { tag = "var", contents = "love.filesystem.getRealDirectory", value = love.filesystem.getRealDirectory},
	["is-file"] = { tag = "var", contents = "love.filesystem.isFile", value = love.filesystem.isFile},
	["read"] = { tag = "var", contents = "love.filesystem.read", value = love.filesystem.read},
	["is-directory"] = { tag = "var", contents = "love.filesystem.isDirectory", value = love.filesystem.isDirectory},
	["get-source-base-directory"] = { tag = "var", contents = "love.filesystem.getSourceBaseDirectory", value = love.filesystem.getSourceBaseDirectory},
}