if not love then love = {} end
if not love.window then love.window = {} end
return {
	["set-fullscreen"] = { tag = "var", contents = "love.window.setFullscreen", value = love.window.setFullscreen},
	["request-attention"] = { tag = "var", contents = "love.window.requestAttention", value = love.window.requestAttention},
	["is-display-sleep-enabled"] = { tag = "var", contents = "love.window.isDisplaySleepEnabled", value = love.window.isDisplaySleepEnabled},
	["is-created"] = { tag = "var", contents = "love.window.isCreated", value = love.window.isCreated},
	["is-maximized"] = { tag = "var", contents = "love.window.isMaximized", value = love.window.isMaximized},
	["get-mode"] = { tag = "var", contents = "love.window.getMode", value = love.window.getMode},
	["is-visible"] = { tag = "var", contents = "love.window.isVisible", value = love.window.isVisible},
	["minimize"] = { tag = "var", contents = "love.window.minimize", value = love.window.minimize},
	["get-display-name"] = { tag = "var", contents = "love.window.getDisplayName", value = love.window.getDisplayName},
	["get-pixel-scale"] = { tag = "var", contents = "love.window.getPixelScale", value = love.window.getPixelScale},
	["is-open"] = { tag = "var", contents = "love.window.isOpen", value = love.window.isOpen},
	["from-pixels"] = { tag = "var", contents = "love.window.fromPixels", value = love.window.fromPixels},
	["set-mode"] = { tag = "var", contents = "love.window.setMode", value = love.window.setMode},
	["to-pixels"] = { tag = "var", contents = "love.window.toPixels", value = love.window.toPixels},
	["get-title"] = { tag = "var", contents = "love.window.getTitle", value = love.window.getTitle},
	["has-mouse-focus"] = { tag = "var", contents = "love.window.hasMouseFocus", value = love.window.hasMouseFocus},
	["get-icon"] = { tag = "var", contents = "love.window.getIcon", value = love.window.getIcon},
	["get-desktop-dimensions"] = { tag = "var", contents = "love.window.getDesktopDimensions", value = love.window.getDesktopDimensions},
	["get-fullscreen-modes"] = { tag = "var", contents = "love.window.getFullscreenModes", value = love.window.getFullscreenModes},
	["set-title"] = { tag = "var", contents = "love.window.setTitle", value = love.window.setTitle},
	["get-fullscreen"] = { tag = "var", contents = "love.window.getFullscreen", value = love.window.getFullscreen},
	["get-position"] = { tag = "var", contents = "love.window.getPosition", value = love.window.getPosition},
	["close"] = { tag = "var", contents = "love.window.close", value = love.window.close},
	["set-display-sleep-enabled"] = { tag = "var", contents = "love.window.setDisplaySleepEnabled", value = love.window.setDisplaySleepEnabled},
	["set-icon"] = { tag = "var", contents = "love.window.setIcon", value = love.window.setIcon},
	["set-position"] = { tag = "var", contents = "love.window.setPosition", value = love.window.setPosition},
	["show-message-box"] = { tag = "var", contents = "love.window.showMessageBox", value = love.window.showMessageBox},
	["get-display-count"] = { tag = "var", contents = "love.window.getDisplayCount", value = love.window.getDisplayCount},
	["maximize"] = { tag = "var", contents = "love.window.maximize", value = love.window.maximize},
	["has-focus"] = { tag = "var", contents = "love.window.hasFocus", value = love.window.hasFocus},
}